### ISSUE TITLE
Errors when at least one service is unreachable

### ISSUE THREAD

**Issue by 1tgr** [rebuy-de/exporter-merger#5]
The `/metrics` endpoint returns a 500 error if at least one of the URLs can't be reached (eg if the service has crashed). It would be helpful if the rest of the metrics were returned anyway when this happens.

It could even expose an `ok: 1`|`0` metric labelled with each URL, so we can track when services go down.

**Comment by paskal** [comment]
Because of this behavior I have problems with all metrics in https://github.com/rebuy-de/nginx-exporter/issues/16. To be fair, without exposing metric about which URL OK and which is not and without current behavior (of breaking all metrics) I wouldn't know otherwise, so it should be fixed at the same time as metric is introduced.

**Comment by der-eismann** [comment]
Closing because we are archiving this repo.
